import { Lang } from "@/types";

export const API_URL = process.env.NEXT_PUBLIC_API_URL;
export const WS_URL = process.env.NEXT_PUBLIC_WS_URL;

export const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  ja: {
    // ...既存の翻訳...
    helpTitle: "あそびかた",
    helpContent:
      "・相手の伏せカードをタップして数字を予想します\n・数字が当たればカードが公開されます\n・外れると自分のカードが公開されます\n・残りのデッキ枚数や場の状況を見て推理しましょう",
    reconnecting: "通信が切れました。再接続しています...",
    welcomeTitle: "Binarily（バイナリリー）",
    welcomeDesc: "ルーム番号を入力して参加するか、\n新しい部屋を作って友達を招待しましょう。",
    roomLabel: "ルーム番号",
    join: "部屋に入る",
    or: "または",
    createRoom: "新しい部屋を作る",
    statusLabel: "ステータス",
    waiting: "対戦相手を待っています...",
    yourTurn: "あなたの番です",
    opponentTurn: "相手の番です",
    online: "オンライン",
    offline: "オフライン",
    field: "場",
    stay: "パス (Stay)",
    yourHand: "あなたの手札",
    opponentHand: "相手の手札",
    guessTitle: "数字を推理",
    guessDesc: "このカードの数字は何だと思いますか？",
    cancel: "キャンセル",
    win: "YOU WIN!",
    lose: "YOU LOSE...",
    winMsg: "おめでとうございます！あなたの勝利です🎉",
    loseMsg: "残念... 次は勝ちましょう！💪",
    replay: "もう一度遊ぶ",
    roomIdLabel: "ルームID",
    logs: "対戦ログ",
    lastAction: "直前の動き",
    // ★追加
    small: "小さい",
    large: "大きい",
    guessed: "予想: ",
    logAttacked: "相手の #{i} を {n} と予想",
    logDefended: "自分の #{i} を {n} と予想されました",
    logRevealed: "カードが公開されました",
    // Tutorial
    tutIntroTitle: "チュートリアルへようこそ",
    tutIntroDesc: "実際にプレイしながら、ゲームのルールと勝ち方をサクッと学びましょう。",
    tutHandTitle: "手札のルール",
    tutHandDesc: "あなたの手札を見てください。\nカードは必ず「左から小さい順」に並んでいます。\nもし同じ数字なら「黒が左」になります。これは絶対のルールです。",
    tutDrawTitle: "カードを引く",
    tutDrawDesc: "あなたの番です。まずは山札からカードを1枚引きます。\n今回は「白の4」を引きました。",
    tutAttackTitle: "攻撃するカードを選ぶ",
    tutAttackDesc: "相手のカードを1枚選んで、数字を予想（攻撃）します。\nまずは「真ん中のカード」をクリックしてみましょう。",
    tutGuessTitle: "数字を当てる",
    tutGuessDesc: "数字を宣言します。相手の手札も、左から小さい順に並んでいます。\n左が「2」、右が「9」なら、その間にある真ん中は...\n「4」と予想してみましょう！",
    tutResultTitle: "成功！",
    tutResultDesc: "正解です！\n予想が当たると、そのカードは表向き（Open）になります。\n成功したら、続けて他のカードを攻撃することもできます。",
    tutStayTitle: "リスクとSTAY",
    tutStayDesc: "もし続けて攻撃して失敗すると、ペナルティとして自分の引いたカードを公開しなければなりません。\n今はリスクを避けて、ここで「STAY（パス）」してターンを終了しましょう。",
    tutEndTitle: "チュートリアル完了",
    tutEndDesc: "基本はこれだけです！\n相手のカードを全て表向きにすれば勝利です。さあ、実戦で腕を試しましょう！",
    tutNext: "次へ",
    tutExit: "終了",
    tutBasicRule: "基本ルール",
    tutBasicRuleDesc: "0〜11の数字が書かれた「黒」と「白」のカードを使います。相手の伏せられたカードの数字をすべて当てた方が勝ちです。",
    tutGoldenRule: "絶対のルール：並び順",
    tutGoldenRuleDesc: "カードは必ず「左から小さい順」に並びます。同じ数字なら「黒」が左です。",
    tutYourTurnDesc: "山札からカードを1枚引きます。そのカードを使って相手のカードを攻撃（推理）します。",
    tutStep1: "相手の伏せカードを選ぶ",
    tutStep2: "数字を宣言する (0-11)",
    tutStep3: "当たれば続けて攻撃可能！",
    tutMissStay: "失敗とパス",
    tutMissStayDesc1: "成功すると、続けて攻撃することもできます。しかし、失敗すると自分の引いたカードを公開しなければなりません。",
    tutMissStayTitle2: "リスクを避けて STAY",
    tutMissStayDesc2: "無理をせず「STAY」で終了すれば、引いたカードを伏せたまま手札に加えられます。",
    tutVictory: "勝利条件",
    tutVictoryTitle: "全て暴く",
    tutVictoryDesc: "相手の手札をすべて「Open」状態にすればあなたの勝ちです！",
  },
  en: {
    // ...Existing translations...
    helpTitle: "How to Play",
    helpContent:
      "- Tap an opponent's card to guess its number.\n- If correct, the card is revealed.\n- If wrong, your card is revealed.\n- Use logic to deduce the numbers.",
    reconnecting: "Reconnecting...",
    welcomeTitle: "Binarily",
    welcomeDesc: "Enter room ID to join, or create a new one.",
    roomLabel: "Room ID",
    join: "Join Game",
    or: "or",
    createRoom: "Create New Room",
    statusLabel: "Status",
    waiting: "Waiting for opponent...",
    yourTurn: "Your Turn",
    opponentTurn: "Opponent's Turn",
    online: "Online",
    offline: "Offline",
    field: "Field",
    stay: "Stay",
    yourHand: "Your Hand",
    opponentHand: "Opponent's Hand",
    guessTitle: "Guess Number",
    guessDesc: "What number is this card?",
    cancel: "Cancel",
    win: "YOU WIN!",
    lose: "YOU LOSE...",
    winMsg: "Congratulations!",
    loseMsg: "Nice try! Play again?",
    replay: "Play Again",
    roomIdLabel: "Room ID",
    logs: "History",
    lastAction: "Last Action",
    // ★Added
    small: "Small",
    large: "Large",
    guessed: "Guess: ",
    logAttacked: "Guessed {n} on #{i}",
    logDefended: "Opponent guessed {n} on your #{i}",
    logRevealed: "Card revealed",
    // Tutorial
    tutIntroTitle: "Welcome to Tutorial",
    tutIntroDesc: "Learn the basic rules and how to win by playing a game.",
    tutHandTitle: "Hand Rules",
    tutHandDesc: "Look at your hand.\nCards are sorted from smallest to largest (left to right).\nIf numbers are equal, Black is on the left. This is the golden rule.",
    tutDrawTitle: "Draw a Card",
    tutDrawDesc: "It's your turn. Draw a card from the deck. You drew a 'White 4'.",
    tutAttackTitle: "Select a Card",
    tutAttackDesc: "Choose an opponent's card to guess (attack).\nLet's click the 'Center Card'.",
    tutGuessTitle: "Guess the Number",
    tutGuessDesc: "Guess the number. Opponent's cards are also sorted.\nIf left is '2' and right is '9', the center must be...\nLet's guess '4'!",
    tutResultTitle: "Success!",
    tutResultDesc: "Correct!\nIf you guess correctly, the card is revealed (Open).\nYou can continue to attack other cards if you succeed.",
    tutStayTitle: "Risk & STAY",
    tutStayDesc: "However, if you miss, you must reveal your drawn card.\nTo avoid this risk, let's 'STAY' (End Turn) for now.",
    tutEndTitle: "Tutorial Complete",
    tutEndDesc: "That's the basics! You win by revealing all opponent's cards. Good luck!",
    tutNext: "Next",
    tutExit: "Exit",
    tutBasicRule: "Basic Rules",
    tutBasicRuleDesc: "Use Black and White cards numbered 0-11. The winner is the one who guesses all of the opponent's hidden cards.",
    tutGoldenRule: "The Golden Rule: Sorting",
    tutGoldenRuleDesc: "Cards are always sorted from smallest to largest (left to right). If numbers are equal, Black is on the left.",
    tutYourTurnDesc: "Draw a card from the deck. Use that card to attack (guess) the opponent's card.",
    tutStep1: "Select an opponent's hidden card",
    tutStep2: "Guess the number (0-11)",
    tutStep3: "If correct, you can attack again!",
    tutMissStay: "Miss & Stay",
    tutMissStayDesc1: "If successful, you can continue attacking. However, if you miss, you must reveal the card you drew.",
    tutMissStayTitle2: "STAY to avoid risk",
    tutMissStayDesc2: "By choosing 'STAY' to end your turn, you can add the drawn card to your hand while keeping it hidden.",
    tutVictory: "Victory",
    tutVictoryTitle: "Reveal All",
    tutVictoryDesc: "You win if you make all of your opponent's cards 'Open'!",
  },
};
