import { Lang } from "@/types";

export const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8787";
export const WS_URL = process.env.NEXT_PUBLIC_WS_URL || "ws://localhost:8787";

export const TRANSLATIONS: Record<Lang, Record<string, string>> = {
  ja: {
    // ...既存の翻訳...
    helpTitle: "あそびかた",
    helpContent:
      "・相手の伏せカードをタップして数字を予想します\n・数字が当たればカードが公開されます\n・外れると自分のカードが公開されます\n・残りのデッキ枚数や場の状況を見て推理しましょう",
    reconnecting: "再接続中...",
    welcomeTitle: "アルゴ・オンライン",
    welcomeDesc: "番号を入力して入室するか、\n新しい部屋を作成してください。",
    roomLabel: "ルーム番号",
    join: "部屋に入る",
    or: "または",
    createRoom: "新しい部屋を作る",
    statusLabel: "ステータス",
    waiting: "対戦相手を待っています...",
    yourTurn: "あなたのターン",
    opponentTurn: "相手のターン",
    online: "接続中",
    offline: "切断",
    field: "場",
    stay: "パス (Stay)",
    yourHand: "あなたの手札",
    opponentHand: "相手の手札",
    guessTitle: "数字を推理",
    guessDesc: "このカードの数字は何だと思いますか？",
    cancel: "やめる",
    win: "YOU WIN!",
    lose: "YOU LOSE...",
    winMsg: "おめでとうございます！完全勝利です。",
    loseMsg: "残念...次は勝てますよ。",
    replay: "もう一度遊ぶ",
    roomIdLabel: "ルームID",
    logs: "履歴",
    lastAction: "直前の動き",
    // ★追加
    small: "小さい",
    large: "大きい",
    guessed: "予想: ",
    logAttacked: "相手の #{i} に {n} を宣言",
    logDefended: "自分の #{i} に {n} と宣言されました",
    logRevealed: "カードが公開されました",
  },
  en: {
    // ...Existing translations...
    helpTitle: "How to Play",
    helpContent:
      "- Tap an opponent's card to guess its number.\n- If correct, the card is revealed.\n- If wrong, your card is revealed.\n- Use logic to deduce the numbers.",
    reconnecting: "Reconnecting...",
    welcomeTitle: "Algo Online",
    welcomeDesc: "Enter room ID to join, or create a new one.",
    roomLabel: "Room ID",
    join: "Join Game",
    or: "or",
    createRoom: "Create New Room",
    statusLabel: "Status",
    waiting: "Waiting for opponent...",
    yourTurn: "Your Turn",
    opponentTurn: "Opponent's Turn",
    online: "Online",
    offline: "Offline",
    field: "Field",
    stay: "Stay",
    yourHand: "Your Hand",
    opponentHand: "Opponent's Hand",
    guessTitle: "Guess Number",
    guessDesc: "What number is this card?",
    cancel: "Cancel",
    win: "YOU WIN!",
    lose: "YOU LOSE...",
    winMsg: "Congratulations!",
    loseMsg: "Nice try! Play again?",
    replay: "Play Again",
    roomIdLabel: "Room ID",
    logs: "History",
    lastAction: "Last Action",
    // ★Added
    small: "Small",
    large: "Large",
    guessed: "Guess: ",
    logAttacked: "Guessed {n} on #{i}",
    logDefended: "Opponent guessed {n} on your #{i}",
    logRevealed: "Card revealed",
  },
};
